<?xml version="1.0" encoding="UTF-8"?><testrun duration="11" footerText="Generated by PyCharm on 23.10.16 11:45" name="Unittest">
    <count name="total" value="64"/>
    <count name="error" value="7"/>
    <count name="failed" value="2"/>
    <count name="passed" value="55"/>
    <config configId="tests" name="Unittest">
        <option name="INTERPRETER_OPTIONS" value=""/>
        <option name="PARENT_ENVS" value="true"/>
        <envs/>
        <option name="SDK_HOME" value="E:\Python27\python.exe"/>
        <option name="WORKING_DIRECTORY" value=""/>
        <option name="IS_MODULE_SDK" value="false"/>
        <option name="ADD_CONTENT_ROOTS" value="true"/>
        <option name="ADD_SOURCE_ROOTS" value="true"/>
        <module name="py_tdd"/>
        <EXTENSION ID="PythonCoverageRunConfigurationExtension" enabled="false" sample_coverage="true" runner="coverage.py"/>
        <option name="SCRIPT_NAME" value="E:/OneDrive/Projekte/Python/A04/bruch/test/testfall.py"/>
        <option name="CLASS_NAME" value=""/>
        <option name="METHOD_NAME" value=""/>
        <option name="FOLDER_NAME" value=""/>
        <option name="TEST_TYPE" value="TEST_SCRIPT"/>
        <option name="PATTERN" value=""/>
        <option name="USE_PATTERN" value="false"/>
        <option name="PUREUNITTEST" value="true"/>
        <option name="PARAMS" value=""/>
        <option name="USE_PARAM" value="false"/>
    </config>
    <suite duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition" name="bruch.test.testfall.TestAddition" status="passed">
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testaddError" name="testaddError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testiAdd" name="testiAdd" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testiAdd2" name="testiAdd2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testiAddError" name="testiAddError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testplus" name="testplus" status="passed"/>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testplus2" name="testplus2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testplus3" name="testplus3" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAddition.testradd" name="testradd" status="passed"/>
    </suite>
    <suite duration="4" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein" name="bruch.test.testfall.TestAllgemein" status="passed">
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testAbs" name="testAbs" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testComplex" name="testComplex" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testFloat" name="testFloat" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testInt" name="testInt" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testInteger" name="testInteger" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testInvert" name="testInvert" status="passed"/>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testNeg" name="testNeg" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testPow" name="testPow" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testPowError1" name="testPowError1" status="passed"/>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testPowError2" name="testPowError2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testRef" name="testRef" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testRef2" name="testRef2" status="passed"/>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.test_makeBruchInt" name="test_makeBruchInt" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.test_makeBruchTypeError" name="test_makeBruchTypeError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testcreateBruchWrongTypeNenner" name="testcreateBruchWrongTypeNenner" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testcreateBruchWrongTypeZaehler" name="testcreateBruchWrongTypeZaehler" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestAllgemein.testcreateBruchZeroError" name="testcreateBruchZeroError" status="passed"/>
    </suite>
    <suite duration="5" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision" name="bruch.test.testfall.TestDivision" status="error">
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testdiv" name="testdiv" status="passed"/>
        <test duration="2" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testdiv2" name="testdiv2" status="failed">
            <output type="stderr">Failure
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 291, in testdiv2
    assert(float(self.b) == 0.75)
AssertionError
</output>
        </test>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testdiv3" name="testdiv3" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testdivTypeError" name="testdivTypeError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testdivZeroError" name="testdivZeroError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testdivZeroError2" name="testdivZeroError2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testiDiv" name="testiDiv" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testiDiv2" name="testiDiv2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testiDivError" name="testiDivError" status="passed"/>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testrdiv" name="testrdiv" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 301, in testrdiv
    self.b2 = 2 / Bruch(2)
TypeError: unsupported operand type(s) for /: &amp;#39;int&amp;#39; and &amp;#39;Bruch&amp;#39;
</output>
        </test>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testrdivError" name="testrdivError" status="passed"/>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestDivision.testrdivZeroError" name="testrdivZeroError" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 315, in testrdivZeroError
    self.assertRaises(ZeroDivisionError, bneu.__rtruediv__, 3)
  File &amp;quot;E:\Python27\lib\unittest\case.py&amp;quot;, line 473, in assertRaises
    callableObj(*args, **kwargs)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 88, in __rtruediv__
    return Bruch.__truediv__(other, self)
TypeError: unbound method __truediv__() must be called with Bruch instance as first argument (got int instance instead)
</output>
        </test>
    </suite>
    <suite duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestIteration" name="bruch.test.testfall.TestIteration" status="passed">
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestIteration.testTuple" name="testTuple" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestIteration.testTuple2" name="testTuple2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestIteration.testTuple3_Error" name="testTuple3_Error" status="passed"/>
    </suite>
    <suite duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation" name="bruch.test.testfall.TestMultiplikation" status="passed">
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testiMul" name="testiMul" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testiMul2" name="testiMul2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testiMulError" name="testiMulError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testmal" name="testmal" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testmal2" name="testmal2" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testmal3" name="testmal3" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testmulError" name="testmulError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestMultiplikation.testrmal" name="testrmal" status="passed"/>
    </suite>
    <suite duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestString" name="bruch.test.testfall.TestString" status="passed">
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestString.teststr" name="teststr" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestString.teststr2" name="teststr2" status="passed"/>
    </suite>
    <suite duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion" name="bruch.test.testfall.TestSubtraktion" status="error">
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testiSub" name="testiSub" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 218, in testiSub
    self.b -= 2
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 101, in __isub__
    return self - other
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 95, in __sub__
    return Bruch.__add(self, other)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 35, in __add
    return Bruch(var1, var2)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 27, in __init__
    raise TypeError
TypeError
</output>
        </test>
        <test duration="1" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testiSub2" name="testiSub2" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 222, in testiSub2
    self.b -= Bruch(2)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 101, in __isub__
    return self - other
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 95, in __sub__
    return Bruch.__add(self, other)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 35, in __add
    return Bruch(var1, var2)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 27, in __init__
    raise TypeError
TypeError
</output>
        </test>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testiSubError" name="testiSubError" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testminus" name="testminus" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 196, in testminus
    self.b = self.b - Bruch(4, 5)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 95, in __sub__
    return Bruch.__add(self, other)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 35, in __add
    return Bruch(var1, var2)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 27, in __init__
    raise TypeError
TypeError
</output>
        </test>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testminus2" name="testminus2" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 200, in testminus2
    self.b = self.b - self.b3
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 95, in __sub__
    return Bruch.__add(self, other)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 35, in __add
    return Bruch(var1, var2)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 27, in __init__
    raise TypeError
TypeError
</output>
        </test>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testminus3" name="testminus3" status="error">
            <output type="stderr">Error
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 204, in testminus3
    self.b2 = self.b - Bruch(1)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 95, in __sub__
    return Bruch.__add(self, other)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 35, in __add
    return Bruch(var1, var2)
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\Bruch.py&amp;quot;, line 27, in __init__
    raise TypeError
TypeError
</output>
        </test>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testrsub" name="testrsub" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestSubtraktion.testrsubError" name="testrsubError" status="failed">
            <output type="stderr">Failure
Traceback (most recent call last):
  File &amp;quot;E:\OneDrive\Projekte\Python\A04\bruch\test\testfall.py&amp;quot;, line 215, in testrsubError
    self.assertRaises(TypeError, self.b2.__rsub__, 2.0)
AssertionError: TypeError not raised
</output>
        </test>
    </suite>
    <suite duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich" name="bruch.test.testfall.TestVergleich" status="passed">
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich.testEqual" name="testEqual" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich.testGE" name="testGE" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich.testGT" name="testGT" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich.testLE" name="testLE" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich.testLT" name="testLT" status="passed"/>
        <test duration="0" locationUrl="python_uttestid:///bruch.test.testfall.TestVergleich.testNotEqual" name="testNotEqual" status="passed"/>
    </suite>
</testrun>
